services:
  backup-to-local-hdd:
    image: eeacms/rsync:${RSYNC_V}
    container_name: backup-local
    command: client
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

      - "${COPYPARTY_DATA}:/source-copyparty:ro"
      - "${BACKUP_COPYPARTY_LOCAL}:/destination-copyparty"

      - "${IMMICH_DATA}postgres/:/source-immich:ro"
      - "${BACKUP_IMMICH_LOCAL}postgres/:/destination-immich"

      - "${VAULTWARDEN_DATA}:/source-waultwarden:ro"
      - "${BACKUP_VAULTWARDEN_LOCAL}:/destination-waultwarden"

      - "${SWINGMUSIC_DATA}:/source-swingmusic:ro"
      - "${BACKUP_SWINGMUSIC_LOCAL}:/destination-swingmusic"
    env_file: 
      - secrets/blackberry.env
      - .env
    environment:
      - CRON_TASK_1=0 3 * * * echo "Starting backup WAULTWARDEN..." && rsync -a --delete --whole-file --stats /source-waultwarden/ /destination-waultwarden/
      - CRON_TASK_2=15 3 * * * echo "Starting backup COPYPARTY..." && rsync -a --delete --whole-file --stats /source-copyparty/ /destination-copyparty/
      - CRON_TASK_3=30 3 * * * echo "Starting backup IMMICH..." && rsync -a --delete --whole-file --stats /source-immich/ /destination-immich/
      - CRON_TASK_3=45 3 * * * echo "Starting backup SWINGMUSIC..." && rsync -a --delete --whole-file --stats /source-swingmusic/ /destination-swingmusic/
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=backup

  backup-to-remote-server:
    image: eeacms/rsync:${RSYNC_V}
    container_name: backup-remote-server
    command: client
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${LOCAL_BACKUP_VOLUME}:/data/:ro"
      - "./secrets/ssh_key:/root/.ssh/id_rsa:ro"
    env_file: 
      - ./secrets/blackberry.env
      - .env
    environment:
      - CRON_TASK_1=0 4 * * * echo "Starting backup remote blueberry..." && rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' -az --delete --numeric-ids --stats /data/ root@blueberry-ts-backup:/data/
      - CRON_TASK_2=0 5 * * * echo "Starting backup remote apple..." && rsync -e 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' -az --delete --numeric-ids --stats /data/ root@apple-ts-backup:/data/
    network_mode: service:ts-backup
    restart: unless-stopped
    depends_on:
      - ts-backup
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=backup

  ts-backup:
    image: tailscale/tailscale:${TAILSCALE_V}
    container_name: ts-backup
    hostname: blackberry-ts-backup
    env_file: 
      - secrets/blackberry.env
      - .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ACCEPT_DNS=true
    volumes:
      - ts-backup-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=backup

volumes:
  ts-backup-state:
    name: "blackberry-ts-backup-state"
