services:
  copyparty:
    image: copyparty/dj:${COPYPARTY_V}
    container_name: copyparty
    restart: unless-stopped
    volumes:
      - "./secrets/copyparty.conf:/cfg/copyparty.conf:ro"

      - "${COPYPARTY_DATA}/share:/share"

      - "${COPYPARTY_DATA}/data:/w"
      - "${SWINGMUSIC_DATA}/music:/music"
      - "${SWINGMUSIC_DATA}/config/swingmusic:/swingmusic"
    env_file: 
      - .env
    environment:
      # enable mimalloc by replacing "NOPE" with "2" for a nice speed-boost (will use twice as much ram)
      LD_PRELOAD: /usr/lib/libmimalloc-secure.so.2
      # ensures log-messages are not delayed (but can reduce speed a tiny bit)
      PYTHONUNBUFFERED: 1
      # disable all TLS features so it is behind proxy
      PRTY_NO_TLS: 1
    expose:
      - 3923
    stop_grace_period: 15s  # thumbnailer is allowed to continue finishing up for 10s after the shutdown signal
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=copyparty

  ssht-copyparty:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-copyparty
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10003
      - SSH_TARGET_HOST=copyparty
      - SSH_TARGET_PORT=3923
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - copyparty
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=copyparty
