services:
  dozzle:
    image: amir20/dozzle:${DOZZLE_V}
    container_name: dozzle
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: 
      - secrets/blackberry.env
      - .env
    environment:
      - DOZZLE_HOSTNAME=blackberry
      - DOZZLE_NO_ANALYTICS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    network_mode: service:ts-dozzle
    depends_on:
      - ts-dozzle
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.name=dozzle

  ts-dozzle:
    image: tailscale/tailscale:${TAILSCALE_V}
    container_name: ts-dozzle
    hostname: blackberry-ts-dozzle
    env_file: 
      - secrets/blackberry.env
      - .env
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-dozzle-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.name=dozzle

volumes:
  ts-dozzle-state:
    name: "blackberry-ts-dozzle-state"
