services:
  immich-server:
    container_name: immich-server
    image: ghcr.io/immich-app/immich-server:v2
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${IMMICH_UPLOAD_LOCATION}:/data"
    env_file: 
      - ./secrets/blackberry/immich.env
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false
    depends_on:
      - redis
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=immich
    ports:
      - '2283:2283'

  immich-machine-learning:
    container_name: immich-machine-learning
    image: ghcr.io/immich-app/immich-machine-learning:v2
    volumes:
      - model-cache:/cache
    env_file: 
      - ./secrets/blackberry/immich.env
      - .env
    restart: unless-stopped
    healthcheck:
      disable: false
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=immich

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f
    healthcheck:
      test: redis-cli ping || exit 1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=immich

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    env_file: 
      - ./secrets/blackberry/immich.env
      - .env
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${IMMICH_DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=immich

  ssht-immich:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-immich
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    restart: unless-stopped
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10002
      - SSH_TARGET_HOST=immich-server
      - SSH_TARGET_PORT=2283
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      immich-server:
        condition: service_healthy
    labels:
      - dev.dozzle.group=immich
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

volumes:
  model-cache:
