services:
  influxdb:
    image: influxdb:2.2
    container_name: influxdb
    restart: unless-stopped
    expose:
      - "8086"
    volumes:
      - "${SCRUTINY_DATA}/influxdb:/var/lib/influxdb2"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 5s
      timeout: 10s
      retries: 20
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=scrutiny

  web:
    image: ghcr.io/analogj/scrutiny:master-web
    container_name: scrutiny-web
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - "${SCRUTINY_DATA}/db:/opt/scrutiny/db"
      - "./secrets/scrutiny.yaml:/opt/scrutiny/config/scrutiny.yaml:ro"
    env_file:
      - .env
    environment:
      SCRUTINY_WEB_INFLUXDB_HOST: 'influxdb'
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=scrutiny

  ssht-scrutiny:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-scrutiny
    restart: unless-stopped
    env_file:
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10009
      - SSH_TARGET_HOST=web
      - SSH_TARGET_PORT=8080
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      web:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=scrutiny

  collector:
    image: ghcr.io/analogj/scrutiny:master-collector
    container_name: scrutiny-collector
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - "/run/udev:/run/udev:ro"
    environment:
      COLLECTOR_API_ENDPOINT: 'http://web:8080'
      COLLECTOR_HOST_ID: 'blackberry'
    depends_on:
      web:
        condition: service_healthy
    devices:
      - "/dev/sda"
      - "/dev/nvme0"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=scrutiny
