services:
  swingmusic:
    image: ghcr.io/tikhonp/swingmusic:latest
    container_name: swingmusic
    restart: unless-stopped
    volumes:
      - "${SWINGMUSIC_DATA}/music:/music"
      - "${SWINGMUSIC_DATA}/config:/config"
    env_file: 
      - .env
    environment:
      - PUID=10001
      - PGID=10001
    expose:
      - 1970
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  ssht-swingmusic:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-swingmusic
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10004
      - SSH_TARGET_HOST=swingmusic
      - SSH_TARGET_PORT=1970
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - swingmusic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  openswingsonic:
    image: ghcr.io/tikhonp/openswingsonic:latest
    container_name: openswingsonic
    restart: unless-stopped
    env_file: 
      - ./secrets/blackberry/swingmusic.env
      - .env
    environment:
      - SWINGSONIC_BASE_URL=https://music.tikhonnnnn.com
      - CRED_PROVIDER=env
    depends_on:
      - swingmusic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
      
  ssht-openswingsonic:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-openswingsonic
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10005
      - SSH_TARGET_HOST=openswingsonic
      - SSH_TARGET_PORT=3000
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - openswingsonic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:v1.2.0
    container_name: metadata-remote
    restart: unless-stopped
    volumes:
      - "${SWINGMUSIC_DATA}/music:/music"
    env_file: 
      - .env
    environment:
      - PUID=10001
      - PGID=10001
      # - SHOW_HIDDEN_FILES=true
    expose:
      - 8338
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
      
  ssht-metadata-remote:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-metadata-remote
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10007
      - SSH_TARGET_HOST=metadata-remote
      - SSH_TARGET_PORT=8338
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - swingmusic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  music-download-bot:
    image: ghcr.io/tikhonp/music-download-bot:v1.0
    container_name: music-download-bot
    restart: unless-stopped
    env_file:
      - ./secrets/blackberry/music-download.env
    environment:
      APPLE_MUSIC_DOWNLOAD_URL: "http://apple-music-api:8080"
    volumes:
      - "${SWINGMUSIC_DATA}/music/qobuz:/downloads"
      - "$HOME/.config/qobuz-dl:/qobuz-dl"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
    depends_on:
      - apple-music-api

  apple-music-wrapper:
    image: ghcr.io/tikhonp/wrapper:latest
    container_name: apple-music-wrapper
    restart: unless-stopped
    environment:
      args: "-H 0.0.0.0"
    volumes:
      - "${SWINGMUSIC_DATA}/apple-music-data/:/app/rootfs/data/"
    expose:
      - "10020"
      - "20020"
      - "30020"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  apple-music-api:
    image: ghcr.io/tikhonp/apple-music-dl-http-wrapper:v1.1.5
    container_name: apple-music-api
    restart: unless-stopped
    environment:
      - PUID=10001
      - PGID=10001
    expose:
      - "8080"
    volumes:
      - "${SWINGMUSIC_DATA}/music/apple-music/:/downloads/"
      - ./secrets/apple-music-config.yaml:/app/config.yaml
    depends_on:
      - apple-music-wrapper
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
  
  musicbrainz-picard:
    image: jlesage/musicbrainz-picard:v25.12.3
    container_name: musicbrainz-picard
    restart: unless-stopped
    environment:
      - USER_ID=10001
      - GROUP_ID=10001
      - TZ=Europe/Moscow
      - DARK_MODE=0
    expose:
      - "5800"
    volumes:
      - "${SWINGMUSIC_DATA}/picard:/config"
      - "${SWINGMUSIC_DATA}/music:/music"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
    # Uncomment the following line to give Picard access to CD-ROM drive
    # devices:
    #   - "/dev/sr0:/dev/sr0"

  ssht-musicbrainz-picard:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-musicbrainz-picard
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10008
      - SSH_TARGET_HOST=musicbrainz-picard
      - SSH_TARGET_PORT=5800
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - musicbrainz-picard
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
