services:
  swingmusic:
    image: ghcr.io/swingmx/swingmusic:${SWINGMUSIC_V}
    container_name: swingmusic
    restart: unless-stopped
    volumes:
      - "${SWINGMUSIC_DATA}/music:/music:ro"
      - "${SWINGMUSIC_DATA}/config:/config"
    env_file: 
      - .env
    expose:
      - 1970
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  ssht-swingmusic:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-swingmusic
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10004
      - SSH_TARGET_HOST=swingmusic
      - SSH_TARGET_PORT=1970
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - swingmusic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  swingsonic:
    image: ghcr.io/tikhonp/swingsonic:latest
    container_name: swingsonic
    restart: unless-stopped
    env_file: 
      - ./secrets/blackberry/swingmusic.env
      - .env
    environment:
      - SERVER_PORT=3000
      - SERVER_URL=https://api.music.tikhonnnnn.com
      - SERVER_API_SUBSONIC_ENABLE=true 
      - SERVER_API_SUBSONIC_OPTIONS_ZW=true # Enable of Zero Width Character Hack
      - SERVER_API_JELLYFIN_ENABLE=false 
      - SERVER_API_EUTERPE=false
      - MUSIC=http://swingmusic:1970
    depends_on:
      - swingmusic
    expose:
      - 3000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
      
  ssht-swingsonic:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-swingsonic
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10005
      - SSH_TARGET_HOST=swingsonic
      - SSH_TARGET_PORT=3000
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - swingsonic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  metadata-remote:
    image: ghcr.io/wow-signal-dev/metadata-remote:${METADATA_REMOTE_V}
    container_name: metadata-remote
    restart: unless-stopped
    volumes:
      - "${SWINGMUSIC_DATA}/music:/music"
    env_file: 
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      # - SHOW_HIDDEN_FILES=true
    expose:
      - 8338
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
      
  ssht-metadata-remote:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-metadata-remote
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10007
      - SSH_TARGET_HOST=metadata-remote
      - SSH_TARGET_PORT=8338
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - swingsonic
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic

  music-download-bot:
    image: ghcr.io/tikhonp/music-download-bot:latest
    container_name: music-download-bot
    restart: unless-stopped
    env_file:
      - ./secrets/blackberry/music-download.env
    volumes:
      - "${SWINGMUSIC_DATA}/music/qobuz:/downloads"
      - "$HOME/.config/qobuz-dl:/qobuz-dl"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=swingmusic
