services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:1.35.2
    environment:
      DOMAIN: "https://secrets.tikhonnnnn.com"
    volumes:
      - "${VAULTWARDEN_DATA}:/data/"
    restart: unless-stopped
    env_file: 
      - ./secrets/blackberry/vaultwarden.env
    expose:
      - 80
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=vaultwarden

  ssht-vaultwarden:
    image: jnovack/autossh:${AUTOSSH_V}
    container_name: ssht-vaultwarden
    restart: unless-stopped
    env_file: 
      - ./secrets/ssh-tunnel.env
      - .env
    environment:
      - SSH_OPTIONS=-o UserKnownHostsFile=/dev/null
      - SSH_TUNNEL_PORT=10006
      - SSH_TARGET_HOST=vaultwarden
      - SSH_TARGET_PORT=80
    volumes:
      - "./secrets/ssh_key:/id_rsa:ro"
    depends_on:
      - vaultwarden
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    labels:
      - dev.dozzle.group=vaultwarden
