services:
  watchtower:
    image: nickfedor/watchtower
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    command: --cleanup --remove-volumes
